services:
  - type: web
    name: Test_case_generator
    env: python
    region: India
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: ${{ OPENAI_API_KEY }}
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata/
