services:
  - type: web
    name: your-app-name
    env: python
    region: your-region
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        value: ${{ OPENAI_API_KEY }}
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata/
