services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "./install_tesseract.sh && pip install -r requirements.txt"
    startCommand: "python app.py"
    build:
      # Install Tesseract OCR
      installPackages:
        - tesseract-ocr
        - libtesseract-dev
